language: php

php:
  - 7.0

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - env >> .env
  - cat .env

script:
  - phpunit tests/TweetieTest.php
